<?php
/** Run only against an isolated QA copy configured for localhost:8099 and tdh_admin_design_qa. */
if(PHP_SAPI!=='cli')exit;
$root=dirname(__DIR__);$GLOBALS['config']=require $root.'/config/config.php';
if(!str_contains($GLOBALS['config']['db_dsn'],'dbname=tdh_admin_design_qa')||$GLOBALS['config']['base_url']!=='http://127.0.0.1:8099')exit('Requires the isolated QA configuration.');
require $root.'/app/functions.php';$jar=$root.'/storage/enhancement-cookies-'.bin2hex(random_bytes(6));$admin=0;$packageId=0;$files=[];$checks=0;
function enhancement_http(string $route,?array $post=null): array {
 global $jar;$c=curl_init(url($route));curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_COOKIEJAR=>$jar,CURLOPT_COOKIEFILE=>$jar,CURLOPT_TIMEOUT=>15]);if($post!==null)curl_setopt_array($c,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$post]);$raw=curl_exec($c);if($raw===false)throw new RuntimeException(curl_error($c));$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);$status=curl_getinfo($c,CURLINFO_RESPONSE_CODE);curl_close($c);return [$status,substr($raw,$size),substr($raw,0,$size)];
}
function enhancement_check(bool $ok,string $label): void {global $checks;if(!$ok)throw new RuntimeException('FAIL '.$label);$checks++;echo 'PASS '.$label.PHP_EOL;}
function enhancement_token(string $html): string {preg_match('/name="csrf" value="([a-f0-9]+)"/',$html,$m);return $m[1]??'';}
try{
 enhancement_check(enhancement_http('admin/packages/preview/1')[0]===303,'private preview requires authentication');
 $password=bin2hex(random_bytes(16));$email='enhancement-'.bin2hex(random_bytes(5)).'@example.invalid';query('INSERT INTO administrators(email,password_hash) VALUES(?,?)',[$email,password_hash($password,PASSWORD_DEFAULT)]);$admin=(int)db()->lastInsertId();[, $html]=enhancement_http('admin/login');enhancement_check(enhancement_http('admin/login',['csrf'=>enhancement_token($html),'email'=>$email,'password'=>$password])[0]===303,'QA administrator login');
 $seed=one("SELECT * FROM packages WHERE status='draft' LIMIT 1");$data=array_diff_key($seed,array_flip(['id','updated_at']));$data['slug']='preview-'.bin2hex(random_bytes(5));$data['name']='Preview QA';$columns=array_keys($data);query('INSERT INTO packages('.implode(',',$columns).') VALUES('.implode(',',array_fill(0,count($columns),'?')).')',array_values($data));$packageId=(int)db()->lastInsertId();
 foreach(['published','draft','published'] as $i=>$status){$file=bin2hex(random_bytes(20)).'.webp';$files[]=$file;$im=imagecreatetruecolor(48,32);imagewebp($im,$root.'/public/media/'.$file);imagedestroy($im);query("INSERT INTO media(owner_type,owner_id,filename,alt_text,credit,license_url,sort_order,status) VALUES('packages',?,?,?,?,?,?,?)",[$packageId,$file,'QA photo '.$i,'QA fixture','',$i,$status]);}
 $ids=array_map('intval',array_column(rows("SELECT id FROM media WHERE owner_type='packages' AND owner_id=? ORDER BY sort_order,id",[$packageId]),'id'));
 [, $html]=enhancement_http('admin/packages/edit/'.$packageId);$csrf=enhancement_token($html);enhancement_check(str_contains($html,'Live preview')&&str_contains($html,'photo-sort-list'),'editor exposes preview and image ordering');
 [$status,$html,$headers]=enhancement_http('admin/packages/preview/'.$packageId);enhancement_check($status===200&&str_contains($html,'Private preview'),'saved draft preview rendered');enhancement_check(str_contains(strtolower($headers),'no-store')&&str_contains(strtolower($headers),'x-robots-tag: noindex'),'preview is private and non-indexable');enhancement_check(str_contains($html,'fieldset disabled')&&str_contains($html,'mobile-sticky'),'preview Booking disabled');enhancement_check(!str_contains($html,$files[1])&&str_contains($html,$files[0]),'preview uses approved image visibility');
 $snapshot=array_map(fn($v)=>$v===null?'':$v,$data);$snapshot['name']='Unsaved <script>alert(1)</script> & travel';$snapshot['csrf']=$csrf;[, $html]=enhancement_http('admin/packages/preview/'.$packageId,$snapshot);enhancement_check(str_contains($html,'Unsaved &lt;script&gt;')&&!str_contains($html,'<script>alert(1)</script>'),'unsaved preview escapes content');enhancement_check(one('SELECT name FROM packages WHERE id=?',[$packageId])['name']==='Preview QA','preview does not save form changes');enhancement_check(enhancement_http('package/'.$data['slug'].'&isAdminPreview=1')[0]===404,'draft remains publicly inaccessible');
 [$status,$html]=enhancement_http('admin/packages/preview/0',$snapshot);enhancement_check($status===200&&str_contains($html,'Unsaved &lt;script&gt;'),'new unsaved package can preview');enhancement_check(enhancement_http('admin/packages/preview/'.$packageId,['csrf'=>'invalid'])[0]===403,'preview POST checks CSRF');
 $endpoint='admin/packages/photos/'.$packageId;$reverse=array_reverse($ids);$post=['csrf'=>$csrf,'operation'=>'reorder','image_order'=>implode(',',$reverse)];enhancement_check(enhancement_http($endpoint,$post)[0]===303,'image ordering saved');$saved=rows("SELECT id,status FROM media WHERE owner_type='packages' AND owner_id=? ORDER BY sort_order,id",[$packageId]);enhancement_check(array_map('intval',array_column($saved,'id'))===$reverse,'database order matches selected order');enhancement_check(media_for('packages',$packageId)[0]['filename']===$files[2],'new cover is first published image');enhancement_check($saved[1]['status']==='draft','ordering does not publish draft images');
 $post['image_order']=implode(',',[$ids[0],$ids[0],$ids[2]]);enhancement_check(str_contains(enhancement_http($endpoint,$post)[1],'images have changed'),'duplicate image IDs rejected');$post['image_order']=implode(',',[$ids[0],$ids[1],999999]);enhancement_check(str_contains(enhancement_http($endpoint,$post)[1],'images have changed'),'foreign image IDs rejected');$post['image_order']=(string)$ids[0];enhancement_check(str_contains(enhancement_http($endpoint,$post)[1],'images have changed'),'stale incomplete order rejected');$post['csrf']='invalid';enhancement_check(enhancement_http($endpoint,$post)[0]===403,'ordering checks CSRF');
 [, $html]=enhancement_http('packages');enhancement_check(!str_contains($html,'package-order.js')&&!str_contains($html,'package-preview.css'),'public pages do not load admin enhancements');echo "Enhancement checks passed: $checks\n";
}finally{if($packageId){query("DELETE FROM media WHERE owner_type='packages' AND owner_id=?",[$packageId]);query('DELETE FROM packages WHERE id=?',[$packageId]);}foreach($files as $file)@unlink($root.'/public/media/'.$file);if($admin)query('DELETE FROM administrators WHERE id=?',[$admin]);@unlink($jar);}
