<?php
if(PHP_SAPI!=='cli')exit;
$root=dirname(__DIR__);$GLOBALS['config']=require $root.'/config/config.php';if(!str_contains($GLOBALS['config']['db_dsn'],'dbname=dream_holidays_local_test'))exit('Only the isolated local database is allowed.');require $root.'/app/functions.php';$path=$root.'/storage/browser-fixture.json';
if(($argv[1]??'')==='clean'){
 if(!is_file($path))exit;$fixture=json_decode(file_get_contents($path),true);
 foreach($fixture['media'] as $id){$m=one('SELECT filename FROM media WHERE id=?',[$id]);if($m){$file=$root.'/public/media/'.$m['filename'];if(is_file($file))unlink($file);query('DELETE FROM media WHERE id=?',[$id]);}}
 foreach(['packages','vehicles','services','reviews','administrators'] as $table)foreach($fixture[$table]??[] as $id)query('DELETE FROM '.$table.' WHERE id=?',[$id]);
 query('DELETE FROM enquiries WHERE interest=?',['Browser fixture enquiry']);query('DELETE FROM settings');foreach($fixture['settings'] as $s)query('INSERT INTO settings(setting_key,setting_value) VALUES(?,?)',[$s['setting_key'],$s['setting_value']]);query('DELETE FROM rate_limits');unlink($path);echo 'Browser fixtures cleaned.'.PHP_EOL;exit;
}
if(is_file($path))exit('Clean existing browser fixtures before creating new ones.');$fixture=['media'=>[],'packages'=>[],'vehicles'=>[],'services'=>[],'reviews'=>[],'administrators'=>[],'settings'=>rows('SELECT * FROM settings')];
foreach(['whatsapp_number'=>'919876543210','why_choose'=>'Approved fixture content for browser testing.'] as $k=>$v)query('INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)',[$k,$v]);
foreach([['browser-domestic','Mountain escape & café','domestic','Mountain fixture',3,'Family'],['browser-international','Island escape','international','Island fixture',6,'Honeymoon']] as [$slug,$name,$category,$destination,$duration,$type]){query('INSERT INTO packages(slug,name,category,destination,duration_days,trip_type,overview,accommodation,transport,meals,inclusions,exclusions,cancellation,featured,latitude,longitude,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,1,11,77,?)',[$slug,$name,$category,$destination,$duration,$type,'Browser fixture only — not real business content.','','','','','','Approved fixture terms','published']);$fixture['packages'][]=(int)db()->lastInsertId();}
query('INSERT INTO vehicles(slug,name,category,seating,air_conditioning,luggage,amenities,rental_terms,status) VALUES(?,?,?,?,?,?,?,?,?)',['browser-van','Browser van','Van',12,'AC','','','Approved fixture rental terms','published']);$fixture['vehicles'][]=(int)db()->lastInsertId();
query('INSERT INTO services(slug,name,description,status) VALUES(?,?,?,?)',['browser-service','Family fixture service','Temporary browser test content','published']);$fixture['services'][]=(int)db()->lastInsertId();
$owners=[['packages',$fixture['packages'][0]],['packages',$fixture['packages'][1]],['vehicles',$fixture['vehicles'][0]],['gallery',0]];
foreach($owners as [$type,$id]){$filename=bin2hex(random_bytes(20)).'.webp';$source=imagecreatefromjpeg($root.'/public/assets/mountains-800.jpg');imagewebp($source,$root.'/public/media/'.$filename,80);imagedestroy($source);query('INSERT INTO media(owner_type,owner_id,gallery_category_id,filename,alt_text,credit,license_url,sort_order,status) VALUES(?,?,1,?,?,?,?,0,?)',[$type,$id,$filename,'Mountain scenic fixture','Unsplash scenic fixture','https://unsplash.com/license','published']);$fixture['media'][]=(int)db()->lastInsertId();}
$fixture['admin_password']=bin2hex(random_bytes(16));query('INSERT INTO administrators(email,password_hash) VALUES(?,?)',['browser-admin@example.invalid',password_hash($fixture['admin_password'],PASSWORD_DEFAULT)]);$fixture['administrators'][]=(int)db()->lastInsertId();file_put_contents($path,json_encode($fixture));echo 'Temporary browser fixtures created.'.PHP_EOL;