<?php
if(PHP_SAPI!=='cli')exit;
$root=dirname(__DIR__);$GLOBALS['config']=require $root.'/config/config.php';
if(!str_contains($GLOBALS['config']['db_dsn'],'dbname=dream_holidays_local_test')||$GLOBALS['config']['base_url']!=='http://127.0.0.1:8098')exit('Integration tests require the isolated local configuration.');
require $root.'/app/functions.php';
$jar=$root.'/storage/http-test-cookies.txt';$checks=0;$fixturePackage=0;$fixtureVehicle=0;$fixtureMedia=[];$fixtureAdmin=0;$enquiryIds=[];$savedSettings=rows('SELECT * FROM settings');
function expect(bool $ok,string $label): void {global $checks;if(!$ok)throw new RuntimeException('FAIL: '.$label);$checks++;echo 'PASS: '.$label.PHP_EOL;}
function http(string $route,array $post=[],bool $send=false): array {global $jar;$c=curl_init(url($route));curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_COOKIEJAR=>$jar,CURLOPT_COOKIEFILE=>$jar,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_TIMEOUT=>15]);if($send){curl_setopt($c,CURLOPT_POST,true);curl_setopt($c,CURLOPT_POSTFIELDS,$post);} $result=curl_exec($c);if($result===false)throw new RuntimeException(curl_error($c));$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);$code=curl_getinfo($c,CURLINFO_RESPONSE_CODE);curl_close($c);return ['code'=>$code,'headers'=>substr($result,0,$size),'body'=>substr($result,$size)];}
function token(array $r,string $name='csrf'): string {preg_match('/name="'.preg_quote($name,'/').'" value="([a-f0-9]+)"/',$r['body'],$m);if(empty($m[1]))throw new RuntimeException('Missing form token '.$name);return $m[1];}
try {
 expect((int)query('SELECT COUNT(*) FROM administrators')->fetchColumn()===0,'test starts with no admin');
 foreach(['','packages','services','vehicles','gallery','contact'] as $route)expect(http($route)['code']===200,'public page responds: '.($route?:'home'));
 expect(http('package/ooty')['code']===404,'draft package inaccessible');expect(!str_contains(http('sitemap.xml')['body'],'package%2Footy'),'draft absent from sitemap');expect(!str_contains(http('')['body'],'Ooty — draft'),'draft content absent from homepage');
 $r=http('admin');expect($r['code']===303&&str_contains($r['headers'],'admin%2Flogin'),'admin routes protected');
 $r=http('setup');$password=bin2hex(random_bytes(14));$r=http('setup',['csrf'=>token($r),'installation_token'=>$GLOBALS['config']['installation_token'],'email'=>'test-admin@example.invalid','password'=>$password],true);expect($r['code']===303,'secure initial setup');$fixtureAdmin=(int)query('SELECT id FROM administrators')->fetchColumn();expect(http('setup')['code']===404,'setup disabled after first admin');
 $r=http('admin/login');$r=http('admin/login',['csrf'=>token($r),'email'=>'test-admin@example.invalid','password'=>$password],true);expect($r['code']===303,'administrator login');expect(str_contains(http('admin')['body'],'Enquiries marked Confirmed'),'dashboard distinguishes enquiry status');
 $r=http('admin/settings');$csrf=token($r);$r=http('admin/settings',['csrf'=>$csrf,'whatsapp_number'=>'+91 invalid'],true);expect(str_contains($r['body'],'digits only'),'invalid Booking number rejected');
 $r=http('admin/settings',['csrf'=>$csrf,'whatsapp_number'=>'919876543210'],true);expect($r['code']===303,'valid Booking number saved');
 $package=['csrf'=>$csrf,'name'=>'Integration & café','slug'=>'integration-fixture','category'=>'domestic','destination'=>'Fixture destination','duration_days'=>'3','trip_type'=>'Family','overview'=>'Integration content only','accommodation'=>'','transport'=>'','meals'=>'','inclusions'=>'','exclusions'=>'','cancellation'=>'Confirmed test terms','starting_price'=>'','currency'=>'INR','featured'=>'1','latitude'=>'11','longitude'=>'77','status'=>'draft'];
 $r=http('admin/packages/new',$package,true);expect($r['code']===303,'admin creates draft package');$fixturePackage=(int)one('SELECT id FROM packages WHERE slug=?',['integration-fixture'])['id'];
 $media=['csrf'=>$csrf,'owner_type'=>'packages','owner_id'=>(string)$fixturePackage,'gallery_category_id'=>'','alt_text'=>'Integration mountain fixture','credit'=>'Unsplash scenic test fixture','license_url'=>'https://unsplash.com/license','sort_order'=>'0','status'=>'published','approved'=>'1','image'=>new CURLFile($root.'/public/assets/mountains-800.jpg','image/jpeg','mountain.jpg')];
 $r=http('admin/media/new',$media,true);expect($r['code']===303,'image upload re-encoded and published');$fixtureMedia=array_column(rows('SELECT id FROM media WHERE owner_type=? AND owner_id=?',['packages',$fixturePackage]),'id');$stored=one('SELECT * FROM media WHERE id=?',[$fixtureMedia[0]]);expect(str_ends_with($stored['filename'],'.webp'),'uploads stored with randomized WebP filename');
 $package['status']='published';$package['approved']='1';$r=http('admin/packages/edit/'.$fixturePackage,$package,true);expect($r['code']===303,'approved package published');$r=http('package/integration-fixture');expect($r['code']===200&&str_contains($r['body'],'Integration &amp; café'),'admin content appears publicly');expect(str_contains(http('packages')['body'],'Request Quote'),'unknown price stays Request Quote');expect(str_contains(http('sitemap.xml')['body'],'integration-fixture'),'published package in sitemap');
 $count=(int)query('SELECT COUNT(*) FROM enquiries')->fetchColumn();$r=http('package/integration-fixture',['csrf'=>token($r),'name'=>'Asha & Arun','departure_city'=>'Chennai','travel_date'=>date('Y-m-d',time()+86400),'adults'=>'2','children'=>'0','message'=>''],true);
 expect($r['code']===303&&str_contains($r['headers'],'https://wa.me/919876543210?text='),'Booking opens configured number');preg_match('/Location: (.*)\r/i',$r['headers'],$loc);$wa=rawurldecode($loc[1]??'');expect(str_contains($wa,'Package: Integration & café')&&str_contains($wa,'Children: 0')&&!str_contains($wa,'Message:'),'Booking message context, Unicode and optional omission');expect((int)query('SELECT COUNT(*) FROM enquiries')->fetchColumn()===$count,'Booking never stores customer details');
 $r=http('package/integration-fixture');$r=http('package/integration-fixture',['csrf'=>token($r),'name'=>'Asha','departure_city'=>'Chennai','travel_date'=>'2000-01-01','adults'=>'0','children'=>'0'],true);expect($r['code']===200&&str_contains($r['body'],'future travel date'),'server booking validation');
 $r=http('contact');$submission=token($r,'submission_key');$post=['csrf'=>token($r),'submission_key'=>$submission,'full_name'=>'<script>alert(1)</script>','mobile'=>'+91 9876543210','email'=>'','interest'=>'Integration fixture','departure_city'=>'Chennai','travel_date'=>date('Y-m-d',time()+86400),'adults'=>'2','children'=>'0','message'=>'Test only'];sleep(2);$r=http('enquiry',$post,true);expect($r['code']===303,'website enquiry POST redirects');$saved=one('SELECT * FROM enquiries WHERE submission_key=?',[$submission]);expect($saved!==null&&str_starts_with($saved['reference'],'TDH-'),'enquiry committed with reference');$enquiryIds[]=$saved['id'];expect(str_contains(http('contact')['body'],'has been saved'),'success after storage');$r=http('enquiry',$post,true);expect((int)query('SELECT COUNT(*) FROM enquiries WHERE submission_key=?',[$submission])->fetchColumn()===1,'duplicate submission does not duplicate storage');
 query("CREATE TRIGGER test_enquiry_storage_failure BEFORE INSERT ON enquiries FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Simulated local test storage failure'");
 try{$r=http('contact');$failurePost=array_replace($post,['csrf'=>token($r),'submission_key'=>token($r,'submission_key'),'interest'=>'Storage failure fixture']);sleep(2);http('enquiry',$failurePost,true);$r=http('contact');expect(str_contains($r['body'],'could not save')&&!str_contains($r['body'],'has been saved'),'database storage failure never reports success');expect(!one('SELECT id FROM enquiries WHERE submission_key=?',[$failurePost['submission_key']]),'failed insert leaves no enquiry record');}finally{query('DROP TRIGGER IF EXISTS test_enquiry_storage_failure');}
 $r=http('admin/enquiries/view/'.$saved['id']);expect(str_contains($r['body'],'&lt;script&gt;')&&!str_contains($r['body'],'<script>alert'),'enquiry input escaped in admin');$r=http('admin/enquiries/view/'.$saved['id'],['csrf'=>token($r),'status'=>'Quoted','note'=>'Integration note'],true);expect($r['code']===303&&one('SELECT status FROM enquiries WHERE id=?',[$saved['id']])['status']==='Quoted','enquiry status update');expect((int)query('SELECT COUNT(*) FROM enquiry_notes WHERE enquiry_id=?',[$saved['id']])->fetchColumn()===1,'internal enquiry note stored');
 $r=http('admin/reviews/new',['csrf'=>$csrf,'customer_name'=>'Test','review_text'=>'Test review','rating'=>'5','verification_note'=>'','status'=>'published','approved'=>'1'],true);expect(str_contains($r['body'],'Verify this review'),'unverified review cannot publish');
 $r=http('admin/media/new',array_replace($media,['image'=>new CURLFile($root.'/public/index.php','image/jpeg','evil.jpg')]),true);expect(str_contains($r['body'],'Only JPEG'),'disguised script upload rejected');
 $r=http('admin/settings',['csrf'=>'invalid','whatsapp_number'=>'919876543210'],true);expect($r['code']===403,'state-changing request rejects invalid CSRF');
 $count=(int)query('SELECT COUNT(*) FROM enquiries')->fetchColumn();
 $vehicle=['csrf'=>$csrf,'name'=>'Fixture van','slug'=>'integration-van','category'=>'Van','seating'=>'12','air_conditioning'=>'AC','luggage'=>'','amenities'=>'','rental_terms'=>'Approved test rental terms','status'=>'draft'];
 $r=http('admin/vehicles/new',$vehicle,true);expect($r['code']===303,'vehicle draft created');$fixtureVehicle=(int)one('SELECT id FROM vehicles WHERE slug=?',['integration-van'])['id'];
 $vehicleMedia=array_replace($media,['owner_type'=>'vehicles','owner_id'=>(string)$fixtureVehicle]);$r=http('admin/media/new',$vehicleMedia,true);expect($r['code']===303,'actual vehicle image upload workflow');$fixtureMedia=[...$fixtureMedia,...array_column(rows('SELECT id FROM media WHERE owner_type=? AND owner_id=?',['vehicles',$fixtureVehicle]),'id')];
 $vehicle['status']='published';$vehicle['approved']='1';$r=http('admin/vehicles/edit/'.$fixtureVehicle,$vehicle,true);expect($r['code']===303,'vehicle publish');$r=http('vehicles');expect(str_contains($r['body'],'Fixture van')&&str_contains($r['body'],'12 passengers'),'vehicle details public');
 $r=http('vehicle-booking',['csrf'=>token($r),'vehicle_id'=>$fixtureVehicle,'travel_date'=>date('Y-m-d',time()+86400),'pickup'=>'Chennai & airport','travellers'=>'8'],true);expect($r['code']===303&&str_contains(rawurldecode($r['headers']),'Vehicle: Fixture van')&&str_contains(rawurldecode($r['headers']),'Pickup Location: Chennai & airport'),'no-JavaScript vehicle context and supplied details');expect((int)query('SELECT COUNT(*) FROM enquiries')->fetchColumn()===$count,'vehicle Booking does not store enquiry');
 $r=http('vehicles');$r=http('vehicle-booking',['csrf'=>token($r),'vehicle_id'=>$fixtureVehicle,'travellers'=>'0'],true);expect($r['code']===422,'vehicle validation on server');
 $r=http('contact');$spam=['csrf'=>token($r),'submission_key'=>token($r,'submission_key'),'website'=>'bot'];$r=http('enquiry',$spam,true);expect($r['code']===303&&!one('SELECT id FROM enquiries WHERE submission_key=?',[$spam['submission_key']]),'spam enquiry not stored');
 $package['status']='draft';$r=http('admin/packages/edit/'.$fixturePackage,$package,true);expect($r['code']===303&&http('package/integration-fixture')['code']===404,'unpublish hides public page');expect(!str_contains(http('sitemap.xml')['body'],'integration-fixture'),'unpublish removes sitemap entry');
 $r=http('admin/settings',['csrf'=>$csrf,'whatsapp_number'=>''],true);$package['status']='published';http('admin/packages/edit/'.$fixturePackage,$package,true);$r=http('package/integration-fixture');expect(str_contains($r['body'],'disabled')&&!str_contains($r['body'],'https://wa.me/'),'missing number disables Booking');
 $r=http('admin/password');$newPassword=bin2hex(random_bytes(14));$r=http('admin/password',['csrf'=>token($r),'current_password'=>$password,'password'=>$newPassword,'confirm_password'=>$newPassword],true);expect($r['code']===303,'password change');$r=http('admin');$csrf=token($r);$r=http('admin/logout',['csrf'=>$csrf],true);expect($r['code']===303&&http('admin')['code']===303,'logout protects subsequent requests');
 $r=http('admin/login');for($i=0;$i<11;$i++)$r=http('admin/login',['csrf'=>token($r),'email'=>'no@example.invalid','password'=>'wrong'],true);expect(str_contains($r['body'],'Too many sign-in attempts'),'login throttling enforced');
 echo 'Integration checks passed: '.$checks.PHP_EOL;
} finally {
 foreach($enquiryIds as $id)query('DELETE FROM enquiries WHERE id=?',[$id]);
 foreach($fixtureMedia as $id){$m=one('SELECT filename FROM media WHERE id=?',[$id]);if($m){$file=$root.'/public/media/'.$m['filename'];if(is_file($file))unlink($file);query('DELETE FROM media WHERE id=?',[$id]);}}
 if($fixtureVehicle)query('DELETE FROM vehicles WHERE id=?',[$fixtureVehicle]);if($fixturePackage)query('DELETE FROM packages WHERE id=?',[$fixturePackage]);if($fixtureAdmin)query('DELETE FROM administrators WHERE id=?',[$fixtureAdmin]);query('DELETE FROM settings');foreach($savedSettings as $s)query('INSERT INTO settings(setting_key,setting_value) VALUES(?,?)',[$s['setting_key'],$s['setting_value']]);query('DELETE FROM rate_limits');if(is_file($jar))unlink($jar);
}