<?php
// Pure configuration/media checks; never contacts Cloudinary or a production database.
if(PHP_SAPI!=='cli')exit;$root=dirname(__DIR__);require $root.'/app/functions.php';$checks=0;
function cloud_check(bool $ok,string $name): void {global $checks;if(!$ok)throw new RuntimeException('FAIL '.$name);$checks++;echo 'PASS '.$name.PHP_EOL;}
$GLOBALS['config']=['base_url'=>'https://example.com','media_driver'=>'local'];$file=str_repeat('a',40).'.webp';cloud_check(media_url($file)==='https://example.com/media/'.$file,'local media URL preserved');cloud_check(media_url('../private.php')==='','invalid media filename rejected');cloud_check(upload_limit_mb()===8,'shared-host upload limit');
$GLOBALS['config']+=['cloudinary_cloud_name'=>'qa-test','cloudinary_api_key'=>'not-a-real-key','cloudinary_api_secret'=>'not-a-real-secret'];$GLOBALS['config']['media_driver']='cloudinary';$GLOBALS['config']['serverless']=true;cloud_check(cloud_media_ready(),'configured cloud settings recognized');cloud_check(media_url($file)==='https://res.cloudinary.com/qa-test/image/upload/dream-holidays/'.str_repeat('a',40).'.webp','cloud media URL uses selected account');cloud_check(upload_limit_mb()===3,'serverless multipart-safe limit');$GLOBALS['config']['cloudinary_api_secret']='';cloud_check(!cloud_media_ready()&&media_url($file)==='','missing cloud configuration is not a placeholder link');$GLOBALS['config']['cloudinary_cloud_name']='qa/../evil';cloud_check(!cloud_media_ready(),'invalid cloud account rejected');
putenv('TDH_DB_HOST=db.example.com');putenv('TDH_DB_PORT=3306');putenv('TDH_DB_NAME=qa_db');putenv('TDH_BASE_URL=https://example.com');$cfg=require $root.'/config/environment.php';cloud_check($cfg['session_driver']==='database'&&$cfg['session_secure']&&$cfg['db_ssl_required'],'serverless secure session and TLS defaults');cloud_check($cfg['clean_urls']&&$cfg['media_driver']==='cloudinary','serverless routing and storage defaults');putenv('TDH_BASE_URL=http://example.com');try{require $root.'/config/environment.php';cloud_check(false,'reject insecure base URL');}catch(RuntimeException){cloud_check(true,'reject insecure base URL');}putenv('TDH_BASE_URL=https://example.com');putenv('TDH_DB_HOST=db.example.com;dbname=wrong');try{require $root.'/config/environment.php';cloud_check(false,'reject DSN injection');}catch(RuntimeException){cloud_check(true,'reject DSN injection');}
putenv("TDH_DB_HOST= \ndb.example.com \n");putenv("TDH_DB_USER=\navnadmin\n");putenv('TDH_DB_PASSWORD= secret with spaces ');$cfg=require $root.'/config/environment.php';
cloud_check($cfg['db_user']==='avnadmin'&&str_contains($cfg['db_dsn'],'host=db.example.com;'),'accidental whitespace removed from connection identifiers');
cloud_check($cfg['db_password']===' secret with spaces ','password whitespace preserved');
putenv('TDH_DB_HOST');putenv('TDH_DB_PORT=70000');putenv('TDH_DB_NAME=invalid/name');putenv('TDH_BASE_URL=not-a-url');
try{require $root.'/config/environment.php';cloud_check(false,'identify invalid variables');}catch(RuntimeException $error){cloud_check($error->getMessage()==='Missing or invalid environment variables: TDH_DB_HOST, TDH_DB_PORT, TDH_DB_NAME, TDH_BASE_URL.','diagnostics identify all invalid variables without values');}
echo "Serverless checks passed: $checks\n";
