<?php /* Public About layout; approved page/settings content stays editable in admin. */ ?>
<section class="container about-hero">
 <div class="about-hero-copy"><span class="eyebrow"><span class="dot"></span> ABOUT THE DREAM HOLIDAYS</span><h1>Every journey starts<br>with a <em>dream.</em></h1><p class="about-lead">Explore memorable journeys with thoughtfully planned tours, comfortable transport, and personalised travel support.</p><div class="actions"><a class="button" href="<?=e(url('packages'))?>">Explore Packages ↗</a><a class="text-link" href="<?=e(url('contact'))?>">Tell us your travel plans →</a></div><div class="about-signature"><span aria-hidden="true">✦</span><span>Travel. Explore. Connect.<br><strong>Your next chapter begins here.</strong></span></div></div>
 <figure class="about-hero-visual"><img src="<?=e(asset('assets/mountains-800.jpg'))?>" alt="A mountain peak rising above clouds, shown as travel inspiration" width="800" height="800" fetchpriority="high"><figcaption>Scenic inspiration · Unsplash</figcaption><div class="about-image-note" aria-hidden="true"><span>ROOM FOR NEW PERSPECTIVES</span><strong>Take the scenic route.</strong></div></figure>
</section>
<section class="container about-intro"><div class="section-head"><div><span class="eyebrow">A LITTLE ABOUT US</span><h2><?=e($page['title'])?></h2></div><span class="about-line" aria-hidden="true"></span></div><div class="about-intro-body"><?=text_block($page['body'])?></div></section>
<section class="container about-values"><div class="section-head"><div><span class="eyebrow">YOUR JOURNEY, YOUR WAY</span><h2>Start with what matters to you.</h2></div></div><div class="grid">
 <?php foreach([['flight','Your destination','A quiet hill escape, a coastal break or somewhere completely new? Tell us where you would like to go.'],['train','Your pace','Share your preferred dates, departure city and the time you have available, so the conversation starts with your plans.'],['bus','Your travel group','Travelling with family, friends or a group? Include your traveller count and transport preferences in your enquiry.']] as [$icon,$heading,$copy]):?>
 <article class="card card-body about-value"><span class="about-value-icon" aria-hidden="true"><svg width="40" height="40" viewBox="0 0 40 40"><use href="<?=e(asset('assets/travel-icons.svg').'#'.$icon)?>"></use></svg></span><h3><?=e($heading)?></h3><p><?=e($copy)?></p></article><?php endforeach?>
</div></section>
<section class="container about-story"><figure class="about-story-photo"><img src="<?=e(asset('assets/about-coast-1000.webp'))?>" srcset="<?=e(asset('assets/about-coast-600.webp'))?> 600w, <?=e(asset('assets/about-coast-1000.webp'))?> 1000w" sizes="(max-width:760px) calc(100vw - 40px), 46vw" alt="Turquoise sea meeting a sandy beach, shown as scenic travel inspiration" width="1000" height="750" loading="lazy"><figcaption>Scenic inspiration · Unsplash</figcaption></figure><div class="about-story-copy"><span class="eyebrow">THOUGHTFUL PLANNING</span><h2>Good journeys begin<br>with a conversation.</h2><?php if(setting('travel_approach')!==''):?><?=text_block(setting('travel_approach'))?><?php else:?><p>Bring your ideas, your questions and your wish list. Start by exploring the published packages, travel services and vehicle listings, then share the arrangements you would like to discuss.</p><p>Each journey has its own details. Refer to the selected package for its itinerary, inclusions and terms, and ask our team to confirm the final arrangements and quotation.</p><?php endif?><a class="text-link" href="<?=e(url('services'))?>">Explore travel services →</a></div></section>
<section class="container about-process"><div class="section-head"><div><span class="eyebrow">FROM AN IDEA TO A PLAN</span><h2>A clear next step, every step.</h2></div></div><div class="grid">
 <?php foreach([['01','Explore your options','Browse published packages or vehicle rentals. Save the name of the journey or vehicle you would like to discuss.'],['02','Share your preferences','Use Booking to review and send your selected details in chat, or submit a separate website enquiry.'],['03','Confirm the details','Our team will confirm availability, price and your booking. Check the quotation, inclusions and cancellation terms before agreeing.']] as [$number,$heading,$copy]):?><article class="card card-body about-step"><span class="about-step-number"><?=e($number)?></span><h3><?=e($heading)?></h3><p><?=e($copy)?></p></article><?php endforeach?>
</div><p class="help">Opening a Booking chat or submitting an enquiry does not confirm a booking.</p></section>
<?php $teamPhotos=media_for('team',0);if(setting('team')!==''||$teamPhotos):?><section class="container about-business"><div class="section-head"><div><span class="eyebrow">THE PEOPLE BEHIND THE PLANS</span><h2>Our team</h2></div></div><?=text_block(setting('team'))?><?php if($teamPhotos):?><div class="gallery-grid"><?php foreach($teamPhotos as $photo):?><figure><?=picture($photo)?><figcaption><?=e($photo['alt_text'])?></figcaption></figure><?php endforeach?></div><?php endif?></section><?php endif?>
<?php if(setting('service_locations')!==''):?><section class="container about-business"><div class="section-head"><div><span class="eyebrow">LET’S FIND YOUR NEXT DESTINATION</span><h2>Service locations</h2></div></div><?=text_block(setting('service_locations'))?></section><?php endif?>
<section class="container about-cta"><div><span class="eyebrow">LET’S MAKE IT YOURS</span><h2>Where will your dream take you?</h2><p>Share your destination, dates and travel preferences. Let’s start planning your next chapter.</p></div><a class="button" href="<?=e(url('contact'))?>#enquiry">Start an enquiry ↗</a></section>
