<?php
$entities=[
 'packages'=>['label'=>'Packages','fields'=>['name'=>'text','slug'=>'slug','category'=>['domestic','international'],'destination'=>'text','duration_days'=>'positive','trip_type'=>'text','overview'=>'textarea','accommodation'=>'textarea','transport'=>'textarea','meals'=>'textarea','inclusions'=>'textarea','exclusions'=>'textarea','cancellation'=>'textarea','starting_price'=>'price','currency'=>['INR'],'featured'=>'checkbox','latitude'=>'latitude','longitude'=>'longitude','status'=>['draft','published']]],
 'itinerary_days'=>['label'=>'Itinerary days','fields'=>['package_id'=>'package','day_number'=>'positive','title'=>'text','description'=>'textarea']],
 'package_options'=>['label'=>'Package options','fields'=>['package_id'=>'package','title'=>'text','description'=>'textarea']],
 'services'=>['label'=>'Services','fields'=>['name'=>'text','slug'=>'slug','description'=>'textarea','status'=>['draft','published']]],
 'vehicles'=>['label'=>'Vehicles','fields'=>['name'=>'text','slug'=>'slug','category'=>['Car','Van','Bus'],'seating'=>'positive','air_conditioning'=>['AC','Non-AC'],'luggage'=>'textarea','amenities'=>'textarea','rental_terms'=>'textarea','status'=>['draft','published']]],
 'gallery_categories'=>['label'=>'Gallery categories','fields'=>['name'=>'text']],
 'media'=>['label'=>'Images & gallery','fields'=>['owner_type'=>['packages','services','vehicles','gallery','team'],'owner_id'=>'owner','gallery_category_id'=>'gallery_category','alt_text'=>'text','credit'=>'text','license_url'=>'optional_url','sort_order'=>'order','status'=>['draft','published']]],
 'reviews'=>['label'=>'Verified reviews','fields'=>['customer_name'=>'text','review_text'=>'textarea','rating'=>['1','2','3','4','5'],'verification_note'=>'textarea','verified'=>'checkbox','status'=>['draft','published']]],
 'pages'=>['label'=>'Pages & policies','fields'=>['slug'=>'slug','title'=>'text','body'=>'textarea','meta_description'=>'text','status'=>['draft','published']]],
];
$settingFields=['whatsapp_number','phone','email','address','hours','maps_embed_url','instagram','facebook','youtube','why_choose','travel_approach','team','service_locations','business_verified','home_supporting_text'];
function admin_icon(string $name): string {
 $paths=['dashboard'=>'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>','packages'=>'<path d="M4 7h16v14H4zM8 7V3h8v4M4 12h16M9 7v14M15 7v14"/>','itinerary_days'=>'<path d="M8 4h13M8 12h13M8 20h13"/><circle cx="3" cy="4" r="1"/><circle cx="3" cy="12" r="1"/><circle cx="3" cy="20" r="1"/>','package_options'=>'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/>','services'=>'<path d="m12 3 3 6 6 3-6 3-3 6-3-6-6-3 6-3z"/>','vehicles'=>'<rect x="3" y="5" width="18" height="13" rx="3"/><path d="M3 12h18M7 18v3M17 18v3M7 8h10"/><circle cx="7" cy="15" r=".6"/><circle cx="17" cy="15" r=".6"/>','media'=>'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="2"/><path d="m3 17 5-5 4 4 4-6 5 7"/>','gallery_categories'=>'<path d="M3 6h7l2 2h9v13H3zM3 6V3h7l2 3h9v2"/>','reviews'=>'<path d="m12 3 3 6 6 1-4 5 1 6-6-3-6 3 1-6-4-5 6-1z"/>','pages'=>'<path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6M9 16h6"/>','enquiries'=>'<rect x="3" y="4" width="18" height="16" rx="3"/><path d="m3 7 9 6 9-6"/>','settings'=>'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/>','password'=>'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3"/>','logout'=>'<path d="M10 3H4v18h6M8 12h13m-4-4 4 4-4 4"/>','arrow'=>'<path d="M5 19 19 5M7 5h12v12"/>'];
 return '<svg class="admin-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'.($paths[$name]??$paths['dashboard']).'</svg>';
}
function admin_nav_link(string $path,string $label,string $icon): void {
 $current=$GLOBALS['route'];$active=$path==='admin'?$current==='admin':($current===$path||str_starts_with($current,$path.'/'));
 echo '<a href="'.e(url($path)).'" '.($active?'aria-current="page"':'').'>'.admin_icon($icon).'<span>'.e($label).'</span>'.($active?'<span class="nav-active-dot" aria-hidden="true"></span>':'').'</a>';
}
function admin_head(string $title,bool $navigation=true): void {
 global $entities;
 echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>'.e($title).' | Dream Holidays Admin</title><link rel="stylesheet" href="'.e(asset('assets/style.css')).'"><link rel="stylesheet" href="'.e(asset('assets/admin.css?v=20261009-qa-fixes')).'"><script src="'.e(asset('assets/admin.js?v=20261009-qa-fixes')).'" defer></script></head><body class="admin '.(!$navigation?'admin-auth':'').'"><a class="skip" href="#admin-main">Skip to content</a><header class="admin-header"><a class="admin-brand" href="'.e(url('admin')).'"><span class="admin-monogram">TD</span><span>The Dream Holidays<small>ADMIN WORKSPACE</small></span></a><div class="admin-header-actions"><a class="website-link" href="'.e(url()).'">View website '.admin_icon('arrow').'</a>';if($navigation)echo '<span class="admin-avatar" aria-label="Administrator">AD</span><button class="admin-menu" type="button" aria-controls="admin-navigation" aria-expanded="false">Menu</button>';echo '</div></header>';
 if($navigation){echo '<div class="admin-layout"><aside id="admin-navigation" class="admin-nav"><span class="nav-group-label">WORKSPACE</span>';admin_nav_link('admin','Overview','dashboard');admin_nav_link('admin/enquiries','Website enquiries','enquiries');echo '<span class="nav-group-label">CONTENT LIBRARY</span>';foreach($entities as $name=>$def)admin_nav_link('admin/'.$name,$def['label'],$name);echo '<span class="nav-group-label">PREFERENCES</span>';admin_nav_link('admin/settings','Business settings','settings');admin_nav_link('admin/password','Change password','password');echo '<div class="sidebar-help"><span class="sidebar-help-icon">✦</span><strong>A little care. A great journey.</strong><p>Review your content before publishing.</p></div><form method="post" action="'.e(url('admin/logout')).'">'.csrf_field().'<button class="logout-button">'.admin_icon('logout').'Log out</button></form></aside>';}
 else echo '<div class="auth-layout"><section class="auth-art"><span class="eyebrow">THE DREAM HOLIDAYS</span><h2>A clear view.<br>A better journey.</h2><p>Your packages, travel content and website enquiries, thoughtfully organised in one workspace.</p><div class="auth-art-tiles"><span>'.admin_icon('packages').'<strong>Plan</strong></span><span>'.admin_icon('media').'<strong>Create</strong></span><span>'.admin_icon('enquiries').'<strong>Connect</strong></span></div><span class="auth-orbit" aria-hidden="true"></span></section>';
 echo '<main id="admin-main" class="admin-main"><div class="admin-page-heading"><div><span class="admin-kicker">'.($navigation?'YOUR WORKSPACE':'WELCOME TO YOUR WORKSPACE').'</span><h1>'.e($title).'</h1></div>'.($navigation?'<span class="workspace-date">'.e(date('D, d M Y')).'</span>':'').'</div>';if(isset($_SESSION['flash'])){echo '<div class="notice" role="status">'.e($_SESSION['flash']).'</div>';unset($_SESSION['flash']);}
}
function admin_end(bool $navigation=true): void { echo '</main></div></body></html>'; }
function admin_error(string $error): void { echo '<div class="notice" role="alert">'.e($error).'</div>'; }
function validate_entity(string $entity,array $fields): array {
 $data=[];
 foreach($fields as $name=>$type){$v=trim((string)($_POST[$name]??''));if($type==='checkbox'){$data[$name]=isset($_POST[$name])?1:0;continue;}
 if(is_array($type)){if(!in_array($v,array_map('strval',$type),true))throw new InvalidArgumentException('Invalid '.str_replace('_',' ',$name).'.');}
 elseif(in_array($type,['positive','owner','order'],true)){if(filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>$type==='positive'?1:0,'max_range'=>$type==='order'?100000:1000000]])===false)throw new InvalidArgumentException('Invalid '.str_replace('_',' ',$name).'.');$v=(int)$v;}
 elseif($type==='package'){if(!one('SELECT id FROM packages WHERE id=?',[(int)$v]))throw new InvalidArgumentException('Select an existing package.');$v=(int)$v;}
 elseif($type==='gallery_category'){$v=$v===''?null:(int)$v;if($v!==null&&!one('SELECT id FROM gallery_categories WHERE id=?',[$v]))throw new InvalidArgumentException('Select an existing gallery category.');}
 elseif($type==='price'){$v=$v===''?null:$v;if($v!==null&&(!preg_match('/^\d{1,10}(?:\.\d{1,2})?$/D',$v)||(float)$v<0))throw new InvalidArgumentException('Provide a valid confirmed price or leave it blank.');}
 elseif($type==='latitude'||$type==='longitude'){if($v==='')$v=null;elseif(!is_numeric($v)||abs((float)$v)>($type==='latitude'?90:180))throw new InvalidArgumentException('Invalid map coordinate.');}
 elseif($type==='slug'){if(!preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/D',$v)||strlen($v)>190)throw new InvalidArgumentException('Use a lowercase URL slug with letters, digits and hyphens.');if($entity==='pages'&&in_array($v,['packages','services','vehicles','gallery','contact','setup','admin','enquiry','sitemap','robots','not-found'],true))throw new InvalidArgumentException('This page slug is reserved.');}
 elseif($type==='optional_url'){if($v!==''&&(!filter_var($v,FILTER_VALIDATE_URL)||!str_starts_with($v,'https://')))throw new InvalidArgumentException('License URL must use HTTPS.');}
 elseif($type==='text'){if($v===''&& !in_array($name,['credit'],true))throw new InvalidArgumentException('Please provide '.str_replace('_',' ',$name).'.');if(strlen($v)>($name==='alt_text'?255:($name==='meta_description'?300:190)))throw new InvalidArgumentException('Text field is too long.');}
 if(is_string($v)&&strlen($v)>($type==='optional_url'?1000:20000))throw new InvalidArgumentException('Content is too long.');$data[$name]=$v;
 }
 if($entity==='media'){
 if(in_array($data['owner_type'],['packages','services','vehicles'],true)&&!one('SELECT id FROM '.$data['owner_type'].' WHERE id=?',[$data['owner_id']]))throw new InvalidArgumentException('Enter the ID of an existing content record for this image.');
 if(in_array($data['owner_type'],['gallery','team'],true))$data['owner_id']=0;
 if($data['status']==='published'&&$data['credit']==='')throw new InvalidArgumentException('Record the photo source/ownership before publishing.');
 }
 if(($data['status']??'')==='published'){
 if(empty($_POST['approved']))throw new InvalidArgumentException('Confirm business approval before publishing.');
 foreach($data as $key=>$value)if(is_string($value)&&preg_match('/\bdraft\b|await(?:ing)? .*approval|placeholder/i',$value))throw new InvalidArgumentException('Remove draft/placeholder text and confirm the facts before publishing.');
 if($entity==='reviews'&&(!$data['verified']||$data['verification_note']===''))throw new InvalidArgumentException('Verify this review and document verification before publishing.');
 if($entity==='packages'&&($data['overview']===''||$data['cancellation']===''))throw new InvalidArgumentException('Package overview and approved cancellation terms are required for publishing.');
 if(in_array($entity,['pages','services'],true)&&($data['body']??$data['description']??'')==='')throw new InvalidArgumentException('Approved content is required before publication.');
 if($entity==='vehicles'&&$data['rental_terms']==='')throw new InvalidArgumentException('Approved rental terms are required for publication.');
 }
 return $data;
}
function upload_image(): ?string {
 if(!isset($_FILES['image'])||$_FILES['image']['error']===UPLOAD_ERR_NO_FILE)return null;
 $f=$_FILES['image'];if($f['error']!==UPLOAD_ERR_OK||$f['size']>8*1024*1024)throw new InvalidArgumentException('Upload a JPEG, PNG or WebP image no larger than 8 MB.');
 if(!is_uploaded_file($f['tmp_name']))throw new InvalidArgumentException('Invalid upload.');
 $mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$types=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($types[$mime]))throw new InvalidArgumentException('Only JPEG, PNG and WebP images are accepted.');
 $dimensions=getimagesize($f['tmp_name']);if(!$dimensions||$dimensions[0]>8000||$dimensions[1]>8000||$dimensions[0]*$dimensions[1]>16000000)throw new InvalidArgumentException('Image dimensions exceed the safe limit (16 megapixels, 8000 pixels per side).');
 if(!extension_loaded('gd'))throw new RuntimeException('Image processing is unavailable. Contact the hosting administrator.');
 $source=imagecreatefromstring(file_get_contents($f['tmp_name']));if(!$source)throw new InvalidArgumentException('Image could not be decoded.');
 $ratio=min(1,1600/$dimensions[0],1600/$dimensions[1]);$target=imagecreatetruecolor((int)max(1,round($dimensions[0]*$ratio)),(int)max(1,round($dimensions[1]*$ratio)));imagealphablending($target,false);imagesavealpha($target,true);imagecopyresampled($target,$source,0,0,0,0,imagesx($target),imagesy($target),$dimensions[0],$dimensions[1]);
 $filename=bin2hex(random_bytes(20)).'.webp';$path=public_dir().'/media/'.$filename;
 if(!imagewebp($target,$path,82)){imagedestroy($source);imagedestroy($target);throw new RuntimeException('Could not store the processed image.');}imagedestroy($source);imagedestroy($target);return $filename;
}
function delete_image_file(string $filename): void {if(preg_match('/^[a-f0-9]{40}\.webp$/D',$filename)){ $path=public_dir().'/media/'.$filename;if(is_file($path))unlink($path);}}
require_once __DIR__.'/package-images.php';
require_once __DIR__.'/package-preview.php';
$error='';$isPost=$_SERVER['REQUEST_METHOD']==='POST';
if($route==='setup'){
 if((int)query('SELECT COUNT(*) FROM administrators')->fetchColumn()>0){http_response_code(404);exit('Setup is disabled.');}
 $token=$GLOBALS['config']['installation_token']??'';
 if(strlen($token)<32||str_contains($token,'REPLACE_')){http_response_code(503);exit('Configure a strong private installation token before setup.');}
 if($isPost){try{check_csrf();if(!rate_limit('setup',5,900))throw new InvalidArgumentException('Too many attempts. Please try later.');if(!hash_equals($token,(string)($_POST['installation_token']??'')))throw new InvalidArgumentException('Invalid installation token.');$email=strtolower(trim((string)($_POST['email']??'')));$password=(string)($_POST['password']??'');if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($email)>190||strlen($password)<12||strlen($password)>72)throw new InvalidArgumentException('Provide a valid email and a password of 12–72 characters.');if(!(int)query("SELECT GET_LOCK('dream_holidays_admin_setup',5)")->fetchColumn())throw new RuntimeException('Setup is busy. Try later.');try{if((int)query('SELECT COUNT(*) FROM administrators')->fetchColumn()>0)throw new InvalidArgumentException('An administrator already exists.');query('INSERT INTO administrators(email,password_hash) VALUES(?,?)',[$email,password_hash($password,PASSWORD_DEFAULT)]);}finally{query("SELECT RELEASE_LOCK('dream_holidays_admin_setup')");}flash('Administrator created. Setup is disabled. Please sign in.');redirect('admin/login');}catch(InvalidArgumentException $ex){$error=$ex->getMessage();}}
 admin_head('Create the initial administrator',false);if($error)admin_error($error);echo '<p>Use the installation token from your private configuration. Setup becomes unavailable after the first account is created.</p><form method="post" class="auth-form">'.csrf_field().'<label>Installation token<input name="installation_token" type="password" autocomplete="off" required></label><label>Administrator email<input name="email" type="email" autocomplete="username" required maxlength="190"></label><label>Password (12–72 characters)<input name="password" type="password" autocomplete="new-password" minlength="12" maxlength="72" required></label><button class="button">Create administrator</button></form>';admin_end(false);return;
}
if($route==='admin/login'){
 if($isPost){try{check_csrf();if(!rate_limit('login',10,900))throw new InvalidArgumentException('Too many sign-in attempts. Try again in 15 minutes.');$email=strtolower(trim((string)($_POST['email']??'')));$account=one('SELECT * FROM administrators WHERE email=?',[$email]);$hash=$account['password_hash']??'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.';$valid=password_verify((string)($_POST['password']??''),$hash);if(!$account||!$valid)throw new InvalidArgumentException('Email or password is incorrect.');session_regenerate_id(true);$_SESSION['admin_id']=$account['id'];$_SESSION['last_active']=time();$_SESSION['csrf']=bin2hex(random_bytes(32));if(password_needs_rehash($hash,PASSWORD_DEFAULT))query('UPDATE administrators SET password_hash=? WHERE id=?',[password_hash($_POST['password'],PASSWORD_DEFAULT),$account['id']]);redirect('admin');}catch(InvalidArgumentException $ex){$error=$ex->getMessage();}}
 admin_head('Administrator sign in',false);if($error)admin_error($error);echo '<form method="post" class="auth-form">'.csrf_field().'<label>Email<input type="email" name="email" autocomplete="username" required maxlength="190"></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button class="button">Sign in</button></form>';admin_end(false);return;
}
require_admin();
if($route==='admin/logout'){if(!$isPost){http_response_code(405);exit;}check_csrf();$_SESSION=[];session_destroy();redirect('admin/login');}
$parts=explode('/',$route);$entity=$parts[1]??'';$action=$parts[2]??'';$id=(int)($parts[3]??0);
if($entity==='password'){
 if($isPost){try{check_csrf();if(!rate_limit('password-change',8,900))throw new InvalidArgumentException('Too many attempts. Try later.');$a=one('SELECT * FROM administrators WHERE id=?',[$_SESSION['admin_id']]);if(!password_verify((string)($_POST['current_password']??''),$a['password_hash']))throw new InvalidArgumentException('Current password is incorrect.');$new=(string)($_POST['password']??'');if(strlen($new)<12||strlen($new)>72||$new!==($_POST['confirm_password']??''))throw new InvalidArgumentException('Use matching passwords of 12–72 characters.');query('UPDATE administrators SET password_hash=? WHERE id=?',[password_hash($new,PASSWORD_DEFAULT),$a['id']]);session_regenerate_id(true);$_SESSION['csrf']=bin2hex(random_bytes(32));flash('Password changed.');redirect('admin/password');}catch(InvalidArgumentException $ex){$error=$ex->getMessage();}}
 admin_head('Change password');if($error)admin_error($error);echo '<form method="post" class="auth-form">'.csrf_field().'<label>Current password<input type="password" name="current_password" autocomplete="current-password" required></label><label>New password<input type="password" name="password" autocomplete="new-password" minlength="12" maxlength="72" required></label><label>Confirm new password<input type="password" name="confirm_password" autocomplete="new-password" required></label><button class="button">Change password</button></form>';admin_end();return;
}
if($entity==='settings'){
 $newLogo=null;$oldLogo=setting('logo_filename');
 if($isPost){try{check_csrf();$values=[];foreach($settingFields as $key){$v=trim((string)($_POST[$key]??''));if(strlen($v)>20000)throw new InvalidArgumentException('Setting value is too long.');if($key==='whatsapp_number'&&$v!==''&&!phone_valid($v))throw new InvalidArgumentException('Booking number must contain country code and digits only (8–15 digits).');if($key==='phone'&&$v!==''&&!preg_match('/^\+?[0-9 ()-]{8,25}$/D',$v))throw new InvalidArgumentException('Provide a valid contact phone number.');if($key==='email'&&$v!==''&&!filter_var($v,FILTER_VALIDATE_EMAIL))throw new InvalidArgumentException('Provide a valid email address.');if(in_array($key,['instagram','facebook','youtube'],true)&&$v!==''&&(!filter_var($v,FILTER_VALIDATE_URL)||!str_starts_with($v,'https://')))throw new InvalidArgumentException('Social links must use valid HTTPS URLs.');if($key==='maps_embed_url'&&$v!==''&&!preg_match('~^https://(?:www\.google\.com/maps/embed|maps\.google\.com/maps)(?:\?|/)~',$v))throw new InvalidArgumentException('Use a Google Maps HTTPS embed URL, not iframe HTML.');if($key==='business_verified')$v=isset($_POST[$key])?'1':'0';$values[$key]=$v;}$newLogo=upload_image();if($newLogo)$values['logo_filename']=$newLogo;db()->beginTransaction();foreach($values as $key=>$v)query('INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)',[$key,$v]);db()->commit();if($newLogo&&$oldLogo)delete_image_file($oldLogo);flash('Business settings saved.');redirect('admin/settings');}catch(Throwable $ex){if(db()->inTransaction())db()->rollBack();if($newLogo)delete_image_file($newLogo);if($ex instanceof InvalidArgumentException||$ex instanceof HttpError)$error=$ex->getMessage();else{error_log((string)$ex);$error='Could not save settings. Please try again.';}}}
 admin_head('Business & homepage settings');if($error)admin_error($error);echo '<p>Leave unknown details blank. All published claims and contacts must be approved. Featured packages are selected in Packages.</p><form method="post" enctype="multipart/form-data">'.csrf_field().'<div class="form-grid">';foreach($settingFields as $key){$v=$_POST[$key]??setting($key);echo '<label>'.e(ucwords(str_replace('_',' ',$key)));if(in_array($key,['address','hours','why_choose','travel_approach','team','service_locations','home_supporting_text'],true))echo '<textarea name="'.e($key).'" rows="5" maxlength="20000">'.e($v).'</textarea>';elseif($key==='business_verified')echo '<input type="checkbox" name="business_verified" value="1" '.($v==='1'?'checked':'').'> I have verified business details for structured data';else echo '<input name="'.e($key).'" value="'.e($v).'" maxlength="1000">';echo '</label>';}echo '</div><fieldset class="logo-upload"><legend>Business logo</legend><p>Upload the exact business logo as PNG, JPEG or WebP (up to 8 MB). Transparent PNG works best. It will replace the header and footer logo automatically.</p><div class="logo-preview">'.brand_markup().'</div><label>Upload / replace logo<input type="file" name="image" accept="image/png,image/jpeg,image/webp"></label></fieldset><button class="button">Save settings</button></form>';admin_end();return;
}
if($entity==='enquiries'){
 $statuses=['New','Contacted','Quoted','Confirmed','Closed'];$record=$id?one('SELECT * FROM enquiries WHERE id=?',[$id]):null;
 if($isPost){check_csrf();if(!$record)throw new RuntimeException('Enquiry not found.');$status=(string)($_POST['status']??'');$note=trim((string)($_POST['note']??''));if(!in_array($status,$statuses,true)||strlen($note)>4000){$error='Invalid status or note length.';}else{db()->beginTransaction();query('UPDATE enquiries SET status=? WHERE id=?',[$status,$id]);if($note!=='')query('INSERT INTO enquiry_notes(enquiry_id,administrator_id,note) VALUES(?,?,?)',[$id,$_SESSION['admin_id'],$note]);db()->commit();flash('Enquiry updated.');redirect('admin/enquiries/view/'.$id);}}
 admin_head($record?'Enquiry '.$record['reference']:'Saved website enquiries');if($error)admin_error($error);echo '<p>These are website form submissions. WhatsApp conversations are not imported. A Confirmed status is an internal enquiry status.</p>';
 if($record){echo '<dl class="details-list">';foreach($record as $key=>$value){if($key==='submission_key')continue;echo '<dt>'.e(ucwords(str_replace('_',' ',$key))).'</dt><dd>'.nl2br(e($value??'')).'</dd>';}echo '</dl><form method="post">'.csrf_field().'<label>Status<select name="status">';foreach($statuses as $s)echo '<option '.($record['status']===$s?'selected':'').'>'.e($s).'</option>';echo '</select></label><label>Add internal note<textarea name="note" maxlength="4000" rows="4"></textarea></label><button class="button">Update enquiry</button></form><h2>Internal notes</h2>';foreach(rows('SELECT n.*,a.email FROM enquiry_notes n JOIN administrators a ON a.id=n.administrator_id WHERE enquiry_id=? ORDER BY n.id DESC',[$id]) as $n)echo '<article class="card card-body"><small>'.e($n['created_at']).' · '.e($n['email']).'</small>'.text_block($n['note']).'</article>';}
 else{$conditions=[];$args=[];$search=substr(trim((string)($_GET['q']??'')),0,190);if($search!==''){$conditions[]='(reference LIKE ? OR full_name LIKE ? OR mobile LIKE ? OR interest LIKE ?)';$args=array_fill(0,4,'%'.$search.'%');}if(in_array($_GET['status']??'',$statuses,true)){$conditions[]='status=?';$args[]=$_GET['status'];}foreach(['from'=>'>=','to'=>'<='] as $key=>$operator)if(preg_match('/^\d{4}-\d{2}-\d{2}$/D',(string)($_GET[$key]??''))){$conditions[]='created_at '.$operator.' ?';$args[]=$_GET[$key].($key==='from'?' 00:00:00':' 23:59:59');}$where=$conditions?' WHERE '.implode(' AND ',$conditions):'';$count=(int)query('SELECT COUNT(*) FROM enquiries'.$where,$args)->fetchColumn();$pg=max(1,(int)($_GET['page']??1));$offset=($pg-1)*30;echo '<form class="filters" method="get"><input type="hidden" name="route" value="admin/enquiries"><label>Search<input name="q" value="'.e($search).'"></label><label>Status<select name="status"><option value="">All</option>';foreach($statuses as $s)echo '<option '.(($_GET['status']??'')===$s?'selected':'').'>'.e($s).'</option>';echo '</select></label><label>From<input name="from" type="date" value="'.e($_GET['from']??'').'"></label><label>To<input name="to" type="date" value="'.e($_GET['to']??'').'"></label><button class="button">Search</button></form><p>'.e($count).' enquiries</p><div class="table-wrap"><table><thead><tr><th>Reference</th><th>Name</th><th>Interest</th><th>Status</th><th>Created</th></tr></thead><tbody>';foreach(rows('SELECT * FROM enquiries'.$where.' ORDER BY id DESC LIMIT 30 OFFSET '.$offset,$args) as $r)echo '<tr><td><a href="'.e(url('admin/enquiries/view/'.$r['id'])).'">'.e($r['reference']).'</a></td><td>'.e($r['full_name']).'</td><td>'.e($r['interest']).'</td><td>'.e($r['status']).'</td><td>'.e($r['created_at']).'</td></tr>';echo '</tbody></table></div><div class="actions">';foreach(['Previous'=>$pg-1,'Next'=>$pg+1] as $label=>$pageNo)if($pageNo>=1&&$pageNo<=ceil($count/30))echo '<a class="button secondary" href="'.e(url('admin/enquiries').'&'.http_build_query(array_merge(array_intersect_key($_GET,array_flip(['q','status','from','to'])),['page'=>$pageNo]))).'">'.e($label).'</a>';echo '</div>';}
 admin_end();return;
}
if(isset($entities[$entity])){
 $def=$entities[$entity];$record=$id?one('SELECT * FROM '.$entity.' WHERE id=?',[$id]):null;
 if($id&&!$record){http_response_code(404);admin_head('Record not found');admin_end();return;}
 if($entity==='packages'&&$action==='preview'){package_preview($record,$def['fields']);return;}
 if($entity==='packages'&&$action==='photos'){if(!$isPost){http_response_code(405);return;}if(!$record){http_response_code(404);return;}handle_package_images($record);return;}
 if($isPost){$newImage=null;try{check_csrf();db()->beginTransaction();if($record&&in_array($entity,['packages','vehicles'],true))$record=one('SELECT * FROM '.$entity.' WHERE id=? FOR UPDATE',[$id]);
 if($action==='delete'){
 if(!$record)throw new InvalidArgumentException('Record not found.');$files=[];
 if(in_array($entity,['packages','services','vehicles'],true))$files=rows('SELECT filename FROM media WHERE owner_type=? AND owner_id=?',[$entity,$id]);elseif($entity==='media')$files=[['filename'=>$record['filename']]];
 $imageOwners=$entity==='media'?lock_image_owners([$record]):[];if($entity==='media'){$current=one('SELECT * FROM media WHERE id=? FOR UPDATE',[$id]);if(!$current||$current['owner_type']!==$record['owner_type']||$current['owner_id']!==$record['owner_id'])throw new InvalidArgumentException('This image changed. Reload the editor and try again.');$files=[['filename'=>$current['filename']]];}if(in_array($entity,['packages','services','vehicles'],true))query('DELETE FROM media WHERE owner_type=? AND owner_id=?',[$entity,$id]);query('DELETE FROM '.$entity.' WHERE id=?',[$id]);assert_listing_images($imageOwners);db()->commit();foreach($files as $f)delete_image_file($f['filename']);flash('Record deleted.');redirect('admin/'.$entity);
 }
 $data=validate_entity($entity,$def['fields']);
 if($entity==='media'){$newImage=upload_image();if(!$record&&!$newImage)throw new InvalidArgumentException('Choose an image file.');if($newImage)$data['filename']=$newImage;}
 if(in_array($entity,['packages','vehicles'],true)&&($data['status']??'')==='published'&&!media_for($entity,$id))throw new InvalidArgumentException('Save as a draft, upload and publish an approved image, then publish this listing.');
 $imageOwners=$entity==='media'?lock_image_owners([$record,$data]):[];if($entity==='media'&&$record){$current=one('SELECT * FROM media WHERE id=? FOR UPDATE',[$id]);if(!$current||$current['owner_type']!==$record['owner_type']||$current['owner_id']!==$record['owner_id'])throw new InvalidArgumentException('This image changed. Reload the editor and try again.');$record=$current;}
 $columns=array_keys($data);if($record){query('UPDATE '.$entity.' SET '.implode(',',array_map(fn($key)=>$key.'=?',$columns)).' WHERE id=?',[...array_values($data),$id]);}else{query('INSERT INTO '.$entity.' ('.implode(',',$columns).') VALUES('.implode(',',array_fill(0,count($columns),'?')).')',array_values($data));$id=(int)db()->lastInsertId();}
 assert_listing_images($imageOwners);db()->commit();if($newImage&&$record)delete_image_file($record['filename']);flash('Saved successfully.');redirect('admin/'.$entity.'/edit/'.$id);
 }catch(InvalidArgumentException $ex){if(db()->inTransaction())db()->rollBack();if($newImage)delete_image_file($newImage);$error=$ex->getMessage();}catch(PDOException $ex){if(db()->inTransaction())db()->rollBack();if($newImage)delete_image_file($newImage);error_log((string)$ex);$error='Could not save. Check that the slug/name or day number is unique, and referenced records exist.';}}
 admin_head($def['label']);if($error)admin_error($error);
 if(in_array($action,['new','edit'],true)||$isPost){echo '<p><a href="'.e(url('admin/'.$entity)).'">← Back to list</a></p><form method="post" enctype="multipart/form-data"><div class="form-grid">'.csrf_field();
 foreach($def['fields'] as $name=>$type){$v=$_POST[$name]??($record[$name]??'');if($type==='checkbox'&&$isPost)$v=isset($_POST[$name]);echo '<label>'.e(ucwords(str_replace('_',' ',$name)));
 if(is_array($type)){echo '<select name="'.e($name).'">';foreach($type as $option)echo '<option value="'.e($option).'" '.((string)$v===(string)$option?'selected':'').'>'.e(ucfirst($option)).'</option>';echo '</select>';}
 elseif($type==='package'||$type==='gallery_category'){echo '<select name="'.e($name).'">';if($type==='gallery_category')echo '<option value="">None</option>';foreach(rows('SELECT id,name FROM '.($type==='package'?'packages':'gallery_categories').' ORDER BY id') as $opt)echo '<option value="'.e($opt['id']).'" '.((string)$v===(string)$opt['id']?'selected':'').'>#'.e($opt['id']).' '.e($opt['name']).'</option>';echo '</select>';}
 elseif($type==='textarea')echo '<textarea name="'.e($name).'" rows="5" maxlength="20000">'.e($v).'</textarea>';
 elseif($type==='checkbox')echo '<input type="checkbox" name="'.e($name).'" value="1" '.($v?'checked':'').'>';
 else{echo '<input name="'.e($name).'" value="'.e($v).'" type="'.(in_array($type,['positive','owner','order','price','latitude','longitude'],true)?'number':'text').'"';if(in_array($type,['price','latitude','longitude'],true))echo ' step="any"';if($type==='positive')echo ' min="1"';echo '>';}
 if($name==='owner_id')echo '<small>Use the #ID shown on the package/service/vehicle list. Gallery/team images use 0.</small>';if($name==='starting_price')echo '<small>Leave blank for Request Quote. Enter only a confirmed starting price.</small>';echo '</label>';
 }
 if($entity==='media'){if($record)echo '<div>'.picture($record).'</div>';echo '<label>Upload / replace image<input type="file" name="image" accept="image/jpeg,image/png,image/webp" '.(!$record?'required':'').'><small>Maximum 8 MB / 16 megapixels. Images are re-encoded and resized to at most 1600 pixels.</small></label>';}
 if(isset($def['fields']['status']))echo '<label class="full approval"><input type="checkbox" name="approved" value="1"> I confirm all facts, photographs, prices, promises and policy terms in this record are business-approved for publication.</label>';
 echo '</div><div class="actions"><button class="button">Save</button>';if($entity==='packages')echo '<button class="button secondary" type="submit" formaction="'.e(url('admin/packages/preview/'.($record['id']??0))).'" formtarget="_blank">Live preview</button>';echo '</div></form>';if($entity==='packages'){if($record)package_images_panel($record);else echo '<div class="notice">Save the package first. You can then upload, preview and manage its images on this page.</div>';}if($record)echo '<form method="post" action="'.e(url('admin/'.$entity.'/delete/'.$id)).'" class="delete-form" data-confirm="Delete this record and its related data?">'.csrf_field().'<button class="button danger">Delete record</button></form>';
 }else{echo '<div class="section-head"><p>Draft content is not visible publicly. Edit a record to publish/unpublish it.</p><a class="button" href="'.e(url('admin/'.$entity.'/new')).'">Add new</a></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Record</th><th>Status / relationship</th><th>Action</th></tr></thead><tbody>';$pg=max(1,(int)($_GET['page']??1));$count=(int)query('SELECT COUNT(*) FROM '.$entity)->fetchColumn();foreach(rows('SELECT * FROM '.$entity.' ORDER BY id DESC LIMIT 50 OFFSET '.(($pg-1)*50)) as $r){echo '<tr><td>#'.e($r['id']).'</td><td>'.e($r['name']??$r['title']??$r['customer_name']??$r['alt_text']??('Day '.$r['day_number'])).'</td><td>'.e($r['status']??('Package #'.($r['package_id']??''))).'</td><td><a href="'.e(url('admin/'.$entity.'/edit/'.$r['id'])).'">Edit</a></td></tr>';}echo '</tbody></table></div><p>'.e($count).' records</p><div class="actions">';if($pg>1)echo '<a href="'.e(url('admin/'.$entity).'&page='.($pg-1)).'">Previous</a>';if($pg*50<$count)echo '<a href="'.e(url('admin/'.$entity).'&page='.($pg+1)).'">Next</a>';echo '</div>';}
 admin_end();return;
}
if($entity!==''){http_response_code(404);admin_head('Admin page not found');admin_end();return;}
admin_head('Dashboard');
echo '<section class="dashboard-welcome"><div><span class="welcome-label">A NEW DAY. NEW POSSIBILITIES.</span><h2>Let’s make room for<br>the next great journey.</h2><p>Keep your travel content organised and follow up on your website enquiries.</p><div class="welcome-actions"><a class="button" href="'.e(url('admin/packages/new')).'">+ Add a package</a><a class="welcome-link" href="'.e(url('admin/enquiries')).'">View enquiries →</a></div></div><div class="welcome-art" aria-hidden="true"><span class="welcome-globe">'.admin_icon('services').'</span><span class="welcome-mini one">'.admin_icon('packages').'</span><span class="welcome-mini two">'.admin_icon('vehicles').'</span><span class="welcome-mini three">'.admin_icon('enquiries').'</span></div></section><div class="dashboard-section-heading"><h2>Your business at a glance</h2><span>Live database records</span></div><div class="grid stats-grid">';
$stats=[['Published packages',"SELECT COUNT(*) FROM packages WHERE status='published'",'packages','Visible to customers'],['Draft packages',"SELECT COUNT(*) FROM packages WHERE status='draft'",'pages','Awaiting publication'],['Saved website enquiries','SELECT COUNT(*) FROM enquiries','enquiries','Submitted through the website'],['New enquiries',"SELECT COUNT(*) FROM enquiries WHERE status='New'",'enquiries','Ready for follow-up'],['Enquiries marked Confirmed',"SELECT COUNT(*) FROM enquiries WHERE status='Confirmed'",'reviews','Internal enquiry status'],['Published vehicles',"SELECT COUNT(*) FROM vehicles WHERE status='published'",'vehicles','Approved rental listings']];
foreach($stats as [$label,$sql,$icon,$note])echo '<article class="stat card card-body"><div class="stat-heading"><span>'.e($label).'</span><span class="stat-icon">'.admin_icon($icon).'</span></div><strong>'.e(query($sql)->fetchColumn()).'</strong><small>'.e($note).'</small></article>';
echo '</div><div class="dashboard-columns"><section class="dashboard-panel"><div class="dashboard-section-heading"><h2>Recent website enquiries</h2><a href="'.e(url('admin/enquiries')).'">View all →</a></div>';
$recent=rows('SELECT id,reference,full_name,interest,status,created_at FROM enquiries ORDER BY id DESC LIMIT 5');
if(!$recent)echo '<div class="admin-empty">'.admin_icon('enquiries').'<h3>A fresh start.</h3><p>Website enquiries will appear here when customers submit the enquiry form.</p></div>';
else{echo '<div class="table-wrap"><table><thead><tr><th>Customer</th><th>Interest</th><th>Status</th></tr></thead><tbody>';foreach($recent as $r)echo '<tr><td><a href="'.e(url('admin/enquiries/view/'.$r['id'])).'">'.e($r['full_name']).'</a><small class="table-subtitle">'.e($r['reference']).'</small></td><td>'.e($r['interest']).'</td><td><span class="status-badge" data-status="'.e(strtolower($r['status'])).'">'.e($r['status']).'</span></td></tr>';echo '</tbody></table></div>';}
echo '<p class="panel-footnote">WhatsApp conversations are not automatically imported.</p></section><section class="dashboard-panel quick-actions"><div class="dashboard-section-heading"><h2>Quick actions</h2></div>';
foreach([['admin/packages/new','Build a tour package','Itineraries, pricing and inclusions','packages'],['admin/media/new','Add travel imagery','Upload approved photographs','media'],['admin/settings','Update your business','Contact details, logo and Booking number','settings']] as [$path,$label,$note,$icon])echo '<a href="'.e(url($path)).'"><span class="quick-icon">'.admin_icon($icon).'</span><span><strong>'.e($label).'</strong><small>'.e($note).'</small></span><span aria-hidden="true">→</span></a>';
echo '</section></div><section class="publish-reminder">'.admin_icon('reviews').'<div><h2>Ready to publish?</h2><p>Verify your facts, photo rights, prices and policy terms before content goes live. Confirmed enquiry statuses are internal records, not automatically confirmed WhatsApp bookings.</p></div><a href="'.e(url('admin/pages')).'">Review pages →</a></section>';admin_end();