<?php
/** Editorial guidance only: never creates listings, prices, availability or business claims. */
function page_guide_intro(string $route): void {
 $guides=[
 'packages'=>['FIND YOUR KIND OF ESCAPE','A destination is just the beginning.','Think about the places you want to see, how long you would like to stay and who is travelling with you. Browse the published packages below, or share your wish list for a quotation.','about-coast-1000.webp','A sandy beach and ocean, shown as travel inspiration',[
 ['Mountains & quieter moments','Bring your ideas for hill landscapes, nature walks and time away from the everyday.'],['Coasts & new horizons','Tell us if you are dreaming of sea views, island scenery or a relaxed coastal break.'],['A trip shaped around you','Share your departure city, dates, group size and preferred pace. Final arrangements depend on the confirmed quotation.']]],
 'services'=>['MAKE ROOM FOR YOUR PLANS','Different occasions. A personal starting point.','Whether your idea is a family holiday, time away together or a group journey, tell us what matters to you. The published services below contain the details approved for the business.','mountains-800.jpg','A mountain landscape, shown as scenic travel inspiration',[
 ['Family & time together','Share your group size, children’s ages where relevant, and the pace that suits your travel plans.'],['Groups & organised travel','For college, school or corporate travel enquiries, discuss dates, group numbers, transport and any visit permissions needed.'],['Your special interests','Tell us about honeymoon, devotional or adventure travel interests. Ask which arrangements can be confirmed for your chosen journey.']]],
 'vehicles'=>['THE JOURNEY BETWEEN DESTINATIONS','Plan the ride around your group.','Explore published cars, vans and buses below. Ask about seating, luggage space, air conditioning, pickup points and rental terms before agreeing to the arrangements.','mountains-800.jpg','A mountain route landscape, shown as travel inspiration rather than a vehicle photograph',[
 ['Cars','For a smaller travel group, ask about the actual model, passenger capacity and luggage space.'],['Vans','For travelling together, share your passenger count, luggage needs and pickup location.'],['Buses','For larger groups, discuss the required seating, route, pickup points and confirmed amenities.']]],
 'gallery'=>['A LITTLE INSPIRATION','Picture your next chapter.','From mountain landscapes to coastal horizons, let these scenic photographs spark your travel ideas. The separate business gallery below shows approved trip, destination and vehicle photographs when supplied.','about-coast-1000.webp','Ocean waves and a beach, shown as scenic inspiration',[
 ['Trip moments','Business trip photographs will be added after review and approval.'],['Destination scenery','Use the category filter below to explore approved destination photographs.'],['Actual vehicles','Vehicle photographs in the business gallery must depict the supplied vehicles or approved category.']]],
 'contact'=>['LET’S START WITH YOUR IDEAS','A little detail goes a long way.','Share your destination, departure city, dates and traveller count. Add transport preferences or questions about the itinerary so your enquiry explains the journey you have in mind.','about-coast-1000.webp','A peaceful coastal landscape, shown as scenic travel inspiration',[
 ['A package in mind?','Use its Booking action to review and send the selected package details in your chat.'],['Still exploring?','Submit the website enquiry below. It is stored with a reference so you can identify your request.'],['Before you travel','Availability, prices, inclusions and your booking require confirmation from our team.']]],
 ];$g=$guides[$route];
 echo '<section class="container page-guide-intro"><div class="page-guide-copy"><span class="eyebrow">'.e($g[0]).'</span><h2>'.e($g[1]).'</h2><p>'.e($g[2]).'</p><a class="text-link" href="'.e($route==='contact'?'#enquiry':url('contact').'#enquiry').'">'.($route==='contact'?'Go to enquiry form':'Discuss your travel plans').' →</a></div><figure class="page-guide-photo"><img src="'.e(asset('assets/'.$g[3])).'" alt="'.e($g[4]).'" width="1000" height="700" loading="lazy"><figcaption>Scenic inspiration · Unsplash</figcaption></figure></section><section class="container page-guide-cards" aria-label="Travel planning guidance">';
 foreach($g[5] as $i=>[$title,$body])echo '<article class="guide-card"><span class="guide-number">0'.($i+1).'</span><h3>'.e($title).'</h3><p>'.e($body).'</p></article>';echo '</section>';
 if($route==='gallery'){
  echo '<section class="container inspiration-gallery"><div class="section-head"><div><span class="eyebrow">SCENIC INSPIRATION</span><h2>Mountains or the sea?</h2><p>Licensed inspiration photography, separate from business trip and vehicle photographs.</p></div></div><div class="inspiration-photo-grid">';
  foreach([['mountains-800.jpg','Mountain landscapes'],['about-coast-1000.webp','Coastal horizons']] as [$file,$alt])echo '<figure><button type="button" class="gallery-open" data-src="'.e(asset('assets/'.$file)).'" data-alt="'.e($alt.' · Scenic inspiration').'"><img src="'.e(asset('assets/'.$file)).'" alt="'.e($alt.' shown as scenic inspiration').'" width="800" height="550" loading="lazy"></button><figcaption>'.e($alt).' · Unsplash</figcaption></figure>';echo '</div></section>';
 }
}
function page_guide_end(string $route): void {
 $faq=$route==='vehicles'?[
 ['Is a vehicle shown as available in real time?','No. A listing describes an approved vehicle or category. Our team must confirm availability, the rental quotation and terms for your dates.'],['What should I include in my vehicle enquiry?','Include your pickup location, travel dates, traveller count and luggage requirements. Ask which amenities and charges apply to the actual vehicle.']
 ]:($route==='contact'?[
 ['What happens after I submit an enquiry?','After successful storage, the website shows an enquiry reference. This does not confirm availability or a booking.'],['Does Booking send a message automatically?','No. Booking opens the selected details in your chat for you to review and send yourself. Chat conversations are not automatically imported into website enquiries.']
 ]:[
 ['Does an enquiry or Booking click confirm my trip?','No. Our team will confirm availability, price and your booking. Review the confirmed quotation and arrangements before agreeing.'],['Where do I find the confirmed inclusions and terms?','Check the selected package, service or vehicle details. Ask for clarification if accommodation, meals, transport, tickets or cancellation terms have not been confirmed.']
 ]);
 echo '<section class="container page-guide-faq"><div class="section-head"><div><span class="eyebrow">A FEW HELPFUL DETAILS</span><h2>Before you make your plans.</h2></div></div>';foreach($faq as [$question,$answer])echo '<details><summary>'.e($question).'</summary><p>'.e($answer).'</p></details>';echo '</section>';
 if($route!=='contact')echo '<section class="container page-guide-cta"><div><span class="eyebrow">YOUR NEXT CHAPTER</span><h2>Have a journey in mind?</h2><p>Tell us your destination, dates and travel preferences.</p></div><a class="button" href="'.e(url('contact')).'#enquiry">Start an enquiry →</a></section>';
}
