CREATE TABLE IF NOT EXISTS administrators (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS settings (setting_key VARCHAR(100) PRIMARY KEY, setting_value TEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS packages (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(190) NOT NULL UNIQUE,
 name VARCHAR(190) NOT NULL, category ENUM('domestic','international') NOT NULL DEFAULT 'domestic',
 destination VARCHAR(190) NOT NULL, duration_days SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 trip_type VARCHAR(100) NOT NULL DEFAULT 'Family', overview TEXT NOT NULL,
 accommodation TEXT NOT NULL, transport TEXT NOT NULL, meals TEXT NOT NULL,
 inclusions TEXT NOT NULL, exclusions TEXT NOT NULL, cancellation TEXT NOT NULL,
 starting_price DECIMAL(12,2) NULL, currency CHAR(3) NOT NULL DEFAULT 'INR',
 featured TINYINT NOT NULL DEFAULT 0, latitude DECIMAL(9,6) NULL, longitude DECIMAL(9,6) NULL,
 status ENUM('draft','published') NOT NULL DEFAULT 'draft', updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS itinerary_days (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, package_id INT UNSIGNED NOT NULL,
 day_number SMALLINT UNSIGNED NOT NULL, title VARCHAR(190) NOT NULL, description TEXT NOT NULL,
 UNIQUE(package_id,day_number), FOREIGN KEY(package_id) REFERENCES packages(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS package_options (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, package_id INT UNSIGNED NOT NULL,
 title VARCHAR(190) NOT NULL, description TEXT NOT NULL,
 FOREIGN KEY(package_id) REFERENCES packages(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS services (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(190) NOT NULL UNIQUE, name VARCHAR(190) NOT NULL,
 description TEXT NOT NULL, status ENUM('draft','published') NOT NULL DEFAULT 'draft'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS vehicles (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(190) NOT NULL UNIQUE, name VARCHAR(190) NOT NULL,
 category ENUM('Car','Van','Bus') NOT NULL DEFAULT 'Car', seating SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 air_conditioning ENUM('AC','Non-AC') NOT NULL DEFAULT 'AC', luggage TEXT NOT NULL,
 amenities TEXT NOT NULL, rental_terms TEXT NOT NULL, status ENUM('draft','published') NOT NULL DEFAULT 'draft'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS gallery_categories (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS media (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, owner_type ENUM('packages','services','vehicles','gallery','team') NOT NULL,
 owner_id INT UNSIGNED NOT NULL DEFAULT 0, gallery_category_id INT UNSIGNED NULL,
 filename VARCHAR(100) NOT NULL UNIQUE, alt_text VARCHAR(255) NOT NULL,
 credit VARCHAR(255) NOT NULL, license_url VARCHAR(1000) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 status ENUM('draft','published') NOT NULL DEFAULT 'draft',
 FOREIGN KEY(gallery_category_id) REFERENCES gallery_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS reviews (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, customer_name VARCHAR(190) NOT NULL,
 review_text TEXT NOT NULL, rating TINYINT UNSIGNED NOT NULL DEFAULT 5,
 verification_note TEXT NOT NULL, verified TINYINT NOT NULL DEFAULT 0,
 status ENUM('draft','published') NOT NULL DEFAULT 'draft'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS pages (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(190) NOT NULL UNIQUE,
 title VARCHAR(190) NOT NULL, body TEXT NOT NULL, meta_description VARCHAR(300) NOT NULL,
 status ENUM('draft','published') NOT NULL DEFAULT 'draft'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS enquiries (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, reference VARCHAR(32) NOT NULL UNIQUE,
 submission_key CHAR(64) NOT NULL UNIQUE, full_name VARCHAR(190) NOT NULL, mobile VARCHAR(30) NOT NULL,
 email VARCHAR(190) NULL, interest VARCHAR(190) NOT NULL, departure_city VARCHAR(190) NOT NULL,
 travel_date DATE NOT NULL, adults SMALLINT UNSIGNED NOT NULL, children SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 vehicle_preference VARCHAR(190) NULL, message TEXT NULL,
 status ENUM('New','Contacted','Quoted','Confirmed','Closed') NOT NULL DEFAULT 'New', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS enquiry_notes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, enquiry_id BIGINT UNSIGNED NOT NULL,
 administrator_id INT UNSIGNED NOT NULL, note TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(enquiry_id) REFERENCES enquiries(id) ON DELETE CASCADE,
 FOREIGN KEY(administrator_id) REFERENCES administrators(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS rate_limits (
 bucket CHAR(64) PRIMARY KEY, attempts INT UNSIGNED NOT NULL, expires_at BIGINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
